-- Create Tables matching models.py

-- Users
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    full_name TEXT,
    hashed_password TEXT,
    is_active INTEGER DEFAULT 1, -- keeping as integer for compatibility
    is_admin INTEGER DEFAULT 0,
    role TEXT DEFAULT 'customer'
);

-- Stores
CREATE TABLE IF NOT EXISTS stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    owner_id BIGINT,
    logo_url TEXT,
    banner_url TEXT,
    category TEXT,
    rating FLOAT DEFAULT 0.0,
    response_rate INTEGER DEFAULT 100,
    created_at TEXT,
    phone TEXT,
    address TEXT,
    contact_email TEXT,
    shipping_policy TEXT,
    return_policy TEXT
);

CREATE INDEX IF NOT EXISTS idx_stores_owner_id ON stores(owner_id);

-- Products
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    price FLOAT,
    discount_price FLOAT,
    category TEXT,
    rating FLOAT DEFAULT 0.0,
    reviews INTEGER DEFAULT 0,
    source TEXT,
    image TEXT,
    season TEXT,
    sales_count INTEGER DEFAULT 0,
    store_id BIGINT,
    stock INTEGER DEFAULT 0,
    is_active INTEGER DEFAULT 1,
    sku TEXT,
    images TEXT -- JSON string
);

CREATE INDEX IF NOT EXISTS idx_products_store_id ON products(store_id);
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);

-- Cart Items
CREATE TABLE IF NOT EXISTS cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    product_id BIGINT,
    quantity INTEGER DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_cart_items_user_id ON cart_items(user_id);

-- Wishlist Items
CREATE TABLE IF NOT EXISTS wishlist_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    product_id BIGINT
);

CREATE INDEX IF NOT EXISTS idx_wishlist_items_user_id ON wishlist_items(user_id);

-- Orders
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    total_amount FLOAT,
    status TEXT DEFAULT 'pending',
    created_at TEXT,
    shipping_address TEXT
);

CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);

-- Order Items
CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT,
    product_id BIGINT,
    quantity INTEGER,
    price FLOAT
);

CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);

-- Addresses
CREATE TABLE IF NOT EXISTS addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    full_name TEXT,
    address_line1 TEXT,
    address_line2 TEXT,
    city TEXT,
    state TEXT,
    zip_code TEXT,
    country TEXT,
    phone TEXT,
    is_default INTEGER DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_addresses_user_id ON addresses(user_id);

-- Payment Methods
CREATE TABLE IF NOT EXISTS payment_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    card_type TEXT,
    last_four TEXT,
    expiry_date TEXT,
    card_holder TEXT,
    is_default INTEGER DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_payment_methods_user_id ON payment_methods(user_id);

-- Banners
CREATE TABLE IF NOT EXISTS banners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    subtitle TEXT,
    highlight_text TEXT,
    description TEXT,
    image_url TEXT,
    image_mobile TEXT,
    link_url TEXT,
    action_type TEXT DEFAULT 'url',
    action_value TEXT,
    start_date TEXT,
    end_date TEXT,
    views INTEGER DEFAULT 0,
    clicks INTEGER DEFAULT 0,
    position TEXT DEFAULT 'hero',
    is_active INTEGER DEFAULT 1,
    "order" INTEGER DEFAULT 0 -- 'order' is a reserved keyword
);

-- Store Follows
CREATE TABLE IF NOT EXISTS store_follows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    store_id BIGINT,
    created_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_store_follows_user_id ON store_follows(user_id);
